### ISSUE TITLE
Acho que é um erro na documentação 

### ISSUE THREAD

**Issue by michaelvips** [EvolutionAPI/evolution-docs#25]
Na documentação, na parte de dados sobre instalação em Docker Swarm deploy with Traefik se eu não estiver enganado existe um erro:

![image](https://github.com/EvolutionAPI/evolution-docs/assets/21130174/37095d9e-94c3-4c84-a3b7-c577991cd1f8)

Creio que o correto seria: 

✅ AUTHENTICATION_API_KEY: "YOUR_SUPER_SECURE_KEY" 

❌ AUTHENTICATION_AUTHENTICATION_API_KEY: "YOUR_SUPER_SECURE_KEY"

https://github.com/EvolutionAPI/evolution-docs/blame/d8f6769ed7eda719824a28ae2e80627807571ce0/docs/01-Get%20Started/Installation/Docker.md#L178

**Comment by matheusmaiberg** [comment]
Obrigado pelo feedback, enviei a correção para a aprovação.

**Comment by DavidsonGomes** [comment]
Feito na PR #28
